RoverReachImage:
    ImageProcessing:
        pub_pxCoordinates: '/px_coordinates'
        resize: False #false recommended for quality of image
        resize_width: 640 #only works when resize true
        resize_height: 480 #only woerks when resize true
        

    CalculateBearing:
        sub_pxCoordinates: '/px_coordinates'
        pub_bearing: '/bearing_to_ball'
        camAngleOfView: 110
